@ECHO OFF
SETLOCAL
REM =========================================================================
REM ===    Batch Filename: Build_Win32_Release.bat 
REM ===           Project: PlatformInfo.vcproj 
REM ===  Project Filename: Applications\PlatformInfo\PlatformInfo.vcproj 
REM ===          Platform: Win32 
REM ===            Target: Release 
REM =========================================================================
REM ===    Generated By: CT_BuildConfigTool (CToolsDev-v4.1.1.74) 
REM ===       Copyright: Copyright (c) 1995-2010, Colin Goodall, All Rights Reserved. 
REM ===         Version: CToolsDev-v4.1.1.74 
REM ===       Timestamp: 2025\09\26-17:03:09 utc 
REM =========================================================================


REM =========================================================================
REM === Initialize the environment

pushd  .

IF NOT EXIST "%CT_TOOL_DIR%" GOTO ERROR_CTOOLS_MISSING

SET  PATH=%PATH%;%CT_TOOL_DIR%;
SET  CT_OUTPUT_FLAGS=X

CT_Delete   CT_SetupVSVars_TempOut.txt
CALL        CT_SetupVSVars.bat > CT_SetupVSVars_TempOut.txt
CT_Delete   CT_SetupVSVars_TempOut.txt


REM =========================================================================
REM === Do the Build

CT_Printf       -stdout "Building == CExtend - Applications - PlatformInfo - [Win32-Release]" 



REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - PRE_BUILD_TARGET
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - PRE_BUILD_TARGET



CT_CreateDir   "..\..\Output\BuildLogs" 
CT_Delete      "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Win32.Release.log" 

CT_Printf -stdout "============================================================================="  1>>    "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Win32.Release.log"    2>&1 
CT_Printf -stdout "=== BUILD_TIMESTAMP_START=#@+c; "                                               1>>    "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Win32.Release.log"    2>&1 
CT_Printf -stdout "=== BUILD_TITLE=PlatformInfo "                                                  1>>    "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Win32.Release.log"    2>&1 
CT_Printf -stdout "=== BUILD_TITLE_FULL=CExtend - Applications - PlatformInfo "                    1>>    "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Win32.Release.log"    2>&1 
CT_Printf -stdout "=== BUILD_PLATFORM_TYPE=Win32 "                                                 1>>    "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Win32.Release.log"    2>&1 
CT_Printf -stdout "=== BUILD_TARGET_TYPE=Release "                                                 1>>    "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Win32.Release.log"    2>&1 
CT_Printf -stdout "=== BUILD_PROJECT_FILE_TYPE=VCPROJ "                                            1>>    "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Win32.Release.log"    2>&1 
CT_Printf -stdout "=== BUILD_PROJECT_FILE_NAME=Applications\PlatformInfo\PlatformInfo.vcproj "     1>>    "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Win32.Release.log"    2>&1 
CT_Printf -stdout "=== BUILD_CONFIG_TOOL=CT_BuildConfigTool, CToolsDev-v4.1.1.74 "                 1>>    "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Win32.Release.log"    2>&1 
CT_Printf -stdout "============================================================================="  1>>    "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Win32.Release.log"    2>&1 
DevEnv  "PlatformInfo.vcproj"  /BUILD  "Release|Win32"  /PROJECT  "PlatformInfo"                   1>>    "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Win32.Release.log"    2>&1 
CT_Printf -stdout "============================================================================="  1>>    "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Win32.Release.log"    2>&1 
CT_Printf -stdout "=== BUILD_TIMESTAMP_FINISH=#@+c; "                                              1>>    "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Win32.Release.log"    2>&1 
CT_Printf -stdout "============================================================================="  1>>    "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Win32.Release.log"    2>&1 

SET  CT_OUTPUT_FLAGS=
CT_BuildLog  "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Win32.Release.log" 
SET  CT_OUTPUT_FLAGS=X



REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - POST_BUILD_TARGET
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - POST_BUILD_TARGET



REM =========================================================================
REM === All Done

GOTO  THE_END


REM =========================================================================
REM === Handle Errors

:ERROR_CTOOLS_MISSING
ECHO ERROR: CTools is not installed
GOTO THE_END


REM =========================================================================
REM === The End

:THE_END
ENDLOCAL
popd


