@ECHO OFF
SETLOCAL
REM =========================================================================
REM ===    Batch Filename: Build.bat 
REM ===           Project: PlatformInfo.vcproj 
REM ===  Project Filename: Applications\PlatformInfo\PlatformInfo.vcproj 
REM =========================================================================
REM ===    Generated By: CT_BuildConfigTool (CToolsDev-v4.1.1.74) 
REM ===       Copyright: Copyright (c) 1995-2010, Colin Goodall, All Rights Reserved. 
REM ===         Version: CToolsDev-v4.1.1.74 
REM ===       Timestamp: 2025\09\26-23:54:13 utc 
REM =========================================================================


REM =========================================================================
REM === Initialize the environment

pushd  .


REM =========================================================================
REM === Do the Build

CT_Printf       -stdout "Building == CExtend - Applications - PlatformInfo " 



REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - PRE_BUILD_TARGETS
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - PRE_BUILD_TARGETS




pushd       .
CALL        Build_Win32_Debug.bat
popd

pushd       .
CALL        Build_Win32_Release.bat
popd

pushd       .
CALL        Build_Win64_Debug.bat
popd

pushd       .
CALL        Build_Win64_Release.bat
popd



REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - POST_BUILD_TARGETS
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - POST_BUILD_TARGETS



REM =========================================================================
REM === All Done

GOTO  THE_END


REM =========================================================================
REM === The End

:THE_END
ENDLOCAL
popd


