@ECHO OFF
SETLOCAL
REM =========================================================================
REM ===    Batch Filename: Clean.bat 
REM ===           Project: PlatformInfo.vcproj 
REM ===  Project Filename: Applications\PlatformInfo\PlatformInfo.vcproj 
REM =========================================================================
REM ===    Generated By: CT_BuildConfigTool (CToolsDev-v4.1.1.74) 
REM ===       Copyright: Copyright (c) 1995-2010, Colin Goodall, All Rights Reserved. 
REM ===         Version: CToolsDev-v4.1.1.74 
REM ===       Timestamp: 2025\09\26-23:54:13 utc 
REM =========================================================================


REM =========================================================================
REM === Initialize the environment

pushd  .

IF NOT EXIST "%CT_TOOL_DIR%" GOTO ERROR_CTOOLS_MISSING

SET  PATH=%PATH%;%CT_TOOL_DIR%;
SET  CT_OUTPUT_FLAGS=X


REM =========================================================================
REM === Do the Clean

CT_Printf       -stdout "Cleaning == CExtend - Applications - PlatformInfo " 


REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - PRE_CLEAN_FILES
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - PRE_CLEAN_FILES


CT_CleanVS .

IF EXIST "Win32_Debug"                                                                    CT_Delete "Win32_Debug"                                                                    
IF EXIST "Win32_Release"                                                                  CT_Delete "Win32_Release"                                                                  
IF EXIST "Win64_Debug"                                                                    CT_Delete "Win64_Debug"                                                                    
IF EXIST "Win64_Release"                                                                  CT_Delete "Win64_Release"                                                                  
IF EXIST "Generic_Debug"                                                                  CT_Delete "Generic_Debug"                                                                  
IF EXIST "Generic_Release"                                                                CT_Delete "Generic_Release"                                                                
IF EXIST "LinuxARM_Debug"                                                                 CT_Delete "LinuxARM_Debug"                                                                 
IF EXIST "LinuxARM_Release"                                                               CT_Delete "LinuxARM_Release"                                                               
IF EXIST "LinuxI32_Debug"                                                                 CT_Delete "LinuxI32_Debug"                                                                 
IF EXIST "LinuxI32_Release"                                                               CT_Delete "LinuxI32_Release"                                                               
IF EXIST "LinuxI64_Debug"                                                                 CT_Delete "LinuxI64_Debug"                                                                 
IF EXIST "LinuxI64_Release"                                                               CT_Delete "LinuxI64_Release"                                                               
IF EXIST "PlatformInfo.aps"                                                               CT_Delete "PlatformInfo.aps"                                                               
IF EXIST "PlatformInfo.clw"                                                               CT_Delete "PlatformInfo.clw"                                                               
IF EXIST "PlatformInfo.suo"                                                               CT_Delete "PlatformInfo.suo"                                                               
IF EXIST "PlatformInfo.ncb"                                                               CT_Delete "PlatformInfo.ncb"                                                               
IF EXIST "PlatformInfo.vcproj.before.xml"                                                 CT_Delete "PlatformInfo.vcproj.before.xml"                                                 
IF EXIST "PlatformInfo.vcproj.after.xml"                                                  CT_Delete "PlatformInfo.vcproj.after.xml"                                                  
IF EXIST "PlatformInfo.vcproj.old"                                                        CT_Delete "PlatformInfo.vcproj.old"                                                        
IF EXIST "PlatformInfo.vcproj.*.user"                                                     CT_Delete "PlatformInfo.vcproj.*.user"                                                     
IF EXIST "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Win32.Debug.log"       CT_Delete "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Win32.Debug.log"       
IF EXIST "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Win32.Release.log"     CT_Delete "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Win32.Release.log"     
IF EXIST "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Win64.Debug.log"       CT_Delete "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Win64.Debug.log"       
IF EXIST "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Win64.Release.log"     CT_Delete "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Win64.Release.log"     
IF EXIST "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Generic.Debug.log"     CT_Delete "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Generic.Debug.log"     
IF EXIST "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Generic.Release.log"   CT_Delete "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.Generic.Release.log"   
IF EXIST "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.LinuxARM.Debug.log"    CT_Delete "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.LinuxARM.Debug.log"    
IF EXIST "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.LinuxARM.Release.log"  CT_Delete "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.LinuxARM.Release.log"  
IF EXIST "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.LinuxI32.Debug.log"    CT_Delete "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.LinuxI32.Debug.log"    
IF EXIST "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.LinuxI32.Release.log"  CT_Delete "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.LinuxI32.Release.log"  
IF EXIST "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.LinuxI64.Debug.log"    CT_Delete "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.LinuxI64.Debug.log"    
IF EXIST "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.LinuxI64.Release.log"  CT_Delete "..\..\Output\BuildLogs\CExtend_Applications_PlatformInfo.LinuxI64.Release.log"  


REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - PRE_UPDATE_TOOL
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - PRE_UPDATE_TOOL


CT_BuildUpdateTool -clean -linux .


REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - POST_UPDATE_TOOL
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - POST_UPDATE_TOOL


REM =========================================================================
REM === All Done

GOTO  THE_END


REM =========================================================================
REM === Handle Errors

:ERROR_CTOOLS_MISSING
ECHO ERROR: CTools is not installed
GOTO THE_END


REM =========================================================================
REM === The End

:THE_END
ENDLOCAL
popd


