@ECHO OFF
SETLOCAL
REM =========================================================================
REM ===    Batch Filename: Update.bat 
REM ===           Project: PlatformInfo.vcproj 
REM ===  Project Filename: Applications\PlatformInfo\PlatformInfo.vcproj 
REM =========================================================================
REM ===    Generated By: CT_BuildConfigTool (CToolsDev-v4.1.1.74) 
REM ===       Copyright: Copyright (c) 1995-2010, Colin Goodall, All Rights Reserved. 
REM ===         Version: CToolsDev-v4.1.1.74 
REM ===       Timestamp: 2025\09\26-23:54:13 utc 
REM =========================================================================


REM =========================================================================
REM === Initialize the environment

pushd  .

IF NOT EXIST "%CT_TOOL_DIR%" GOTO ERROR_CTOOLS_MISSING

SET  PATH=%PATH%;%CT_TOOL_DIR%;
SET  CT_OUTPUT_FLAGS=X


REM =========================================================================
REM === Do the Update

CT_Printf -stdout "... Update output for CExtend - Applications - PlatformInfo " 



REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - PRE_UPDATE_TOOL
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - PRE_UPDATE_TOOL



CT_BuildUpdateTool -update -linux .



REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - POST_UPDATE_TOOL
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - POST_UPDATE_TOOL



REM =========================================================================
REM === All Done

GOTO  THE_END


REM =========================================================================
REM === Handle Errors

:ERROR_CTOOLS_MISSING
ECHO ERROR: CTools is not installed
GOTO THE_END


REM =========================================================================
REM === The End

:THE_END
ENDLOCAL
popd


