@ECHO OFF
SETLOCAL
REM =========================================================================
REM ===    Batch Filename: Clean.bat 
REM ===           Project: CT_ProjectConfig.ini 
REM ===  Project Filename: .\CT_ProjectConfig.ini 
REM =========================================================================
REM ===    Generated By: CT_BuildConfigTool (CToolsDev-v4.1.1.74) 
REM ===       Copyright: Copyright (c) 1995-2010, Colin Goodall, All Rights Reserved. 
REM ===         Version: CToolsDev-v4.1.1.74 
REM ===       Timestamp: 2025\09\26-22:22:41 utc 
REM =========================================================================


REM =========================================================================
REM === Initialize the environment

pushd  .

IF NOT EXIST "%CT_TOOL_DIR%" GOTO ERROR_CTOOLS_MISSING

SET  PATH=%PATH%;%CT_TOOL_DIR%;
SET  CT_OUTPUT_FLAGS=X


REM =========================================================================

CT_Printf  -stdout "Cleaning == CExtend " 



REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - BEFORE_SUB_PROJECTS
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - BEFORE_SUB_PROJECTS



REM -------------------------------------------------------------------------
REM --- Libraries
IF NOT EXIST "Libraries"             GOTO SKIP_01_LIBRARIES 
IF NOT EXIST "Libraries\Clean.bat"   GOTO SKIP_01_LIBRARIES 
PUSHD "Libraries" 
CALL  "Clean.bat" 
POPD 
GOTO  FINISH_01_LIBRARIES
:SKIP_01_LIBRARIES
CT_Printf  -stdout "ERROR:  Missing SubProject -- Libraries 
:FINISH_01_LIBRARIES


REM -------------------------------------------------------------------------
REM --- Modules
IF NOT EXIST "Modules"             GOTO SKIP_02_MODULES 
IF NOT EXIST "Modules\Clean.bat"   GOTO SKIP_02_MODULES 
PUSHD "Modules" 
CALL  "Clean.bat" 
POPD 
GOTO  FINISH_02_MODULES
:SKIP_02_MODULES
CT_Printf  -stdout "ERROR:  Missing SubProject -- Modules 
:FINISH_02_MODULES


REM -------------------------------------------------------------------------
REM --- Applications
IF NOT EXIST "Applications"             GOTO SKIP_03_APPLICATIONS 
IF NOT EXIST "Applications\Clean.bat"   GOTO SKIP_03_APPLICATIONS 
PUSHD "Applications" 
CALL  "Clean.bat" 
POPD 
GOTO  FINISH_03_APPLICATIONS
:SKIP_03_APPLICATIONS
CT_Printf  -stdout "ERROR:  Missing SubProject -- Applications 
:FINISH_03_APPLICATIONS


REM -------------------------------------------------------------------------



REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - AFTER_SUB_PROJECTS
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - AFTER_SUB_PROJECTS



REM =========================================================================
REM === Cleaning Output Dir

CT_Delete ".\Output\BuildLogs" 
CT_Delete ".\Output\Libs" 
CT_Delete ".\Output\Include" 
CT_Delete ".\Output\Distrib" 
CT_Delete ".\Output" 


REM =========================================================================
REM === All Done

GOTO  THE_END


REM =========================================================================
REM === Handle Errors

:ERROR_CTOOLS_MISSING
ECHO ERROR: CTools is not installed
GOTO THE_END


REM =========================================================================
REM === The End

:THE_END
ENDLOCAL
popd


