@ECHO OFF
SETLOCAL
REM =========================================================================
REM ===    Batch Filename: Version_Mark.bat 
REM ===           Project: CT_ProjectConfig.ini 
REM ===  Project Filename: .\CT_ProjectConfig.ini 
REM =========================================================================
REM ===    Generated By: CT_BuildConfigTool (CToolsDev-v4.1.1.74) 
REM ===       Copyright: Copyright (c) 1995-2010, Colin Goodall, All Rights Reserved. 
REM ===         Version: CToolsDev-v4.1.1.74 
REM ===       Timestamp: 2025\09\26-22:22:41 utc 
REM =========================================================================


REM =========================================================================
REM === Initialize the environment

pushd  .

IF NOT EXIST "%CT_TOOL_DIR%" GOTO ERROR_CTOOLS_MISSING

SET  PATH=%PATH%;%CT_TOOL_DIR%;
SET  CT_OUTPUT_FLAGS=ZMtDn


REM =========================================================================
REM === Set the prefix string 

SET CT_VERSION_PREFIX=CExtend


REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - MODIFY_VERSION_PREFIX
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - MODIFY_VERSION_PREFIX



REM =========================================================================
REM === Handle Action 


IF "%1" == "" GOTO VERSION_INCREMENT
GOTO VERSION_SET

REM ============================================================
REM === SET VERSION

:VERSION_SET
CT_Printf    "Marking Version For -- CExtend " 
CT_VersionTool  .\  -SetVersionFile %1 -SetVersionProduct %CT_VERSION_PREFIX%-%1
GOTO GENERATE_FILES


REM ============================================================
REM === INCREMENT VERSION

:VERSION_INCREMENT
CT_Printf    "Incrementing Version For -- CExtend " 
CT_VersionTool  .\  -Increment build
GOTO GENERATE_FILES


REM ============================================================
REM === GENERATE FILES

:GENERATE_FILES
CT_VersionTool  .\

GOTO THE_END


REM =========================================================================
REM === Handle Errors

:ERROR_CTOOLS_MISSING
ECHO ERROR: CTools is not installed
GOTO THE_END


REM =========================================================================
REM === The End

:THE_END
ENDLOCAL
popd


