@ECHO OFF
SETLOCAL
REM =========================================================================
REM ===    Batch Filename: Version_Report.bat 
REM ===           Project: CT_ProjectConfig.ini 
REM ===  Project Filename: .\CT_ProjectConfig.ini 
REM =========================================================================
REM ===    Generated By: CT_BuildConfigTool (CToolsDev-v4.1.1.74) 
REM ===       Copyright: Copyright (c) 1995-2010, Colin Goodall, All Rights Reserved. 
REM ===         Version: CToolsDev-v4.1.1.74 
REM ===       Timestamp: 2025\09\26-22:22:41 utc 
REM =========================================================================


REM =========================================================================
REM === Initialize the environment

pushd  .

IF NOT EXIST "%CT_TOOL_DIR%" GOTO ERROR_CTOOLS_MISSING

SET  PATH=%PATH%;%CT_TOOL_DIR%;
SET  CT_OUTPUT_FLAGS=ZMtDn


REM =========================================================================
REM === Extra Flags For Verbose Output 

SET CT_VERSION_FLAGS=-verbose


REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - MODIFY_VERSION_FLAGS
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - MODIFY_VERSION_FLAGS



REM =========================================================================
REM === Report The Version Here 

CT_VersionTool  .\  -Report  %CT_VERSION_FLAGS% 


REM =========================================================================
REM === All Done

GOTO  THE_END


REM =========================================================================
REM === Handle Errors

:ERROR_CTOOLS_MISSING
ECHO ERROR: CTools is not installed
GOTO THE_END


REM =========================================================================
REM === The End

:THE_END
ENDLOCAL
popd


