@ECHO OFF
REM =========================================================================
REM ===    Batch Filename: Version_SetEnv.bat 
REM ===           Project: CT_ProjectConfig.ini 
REM ===  Project Filename: .\CT_ProjectConfig.ini 
REM =========================================================================
REM ===    Generated By: CT_BuildConfigTool (CToolsDev-v4.1.1.74) 
REM ===       Copyright: Copyright (c) 1995-2010, Colin Goodall, All Rights Reserved. 
REM ===         Version: CToolsDev-v4.1.1.74 
REM ===       Timestamp: 2025\09\26-23:54:13 utc 
REM =========================================================================


REM =========================================================================
REM === Initialize the environment

pushd  .

IF NOT EXIST "%CT_TOOL_DIR%" GOTO ERROR_CTOOLS_MISSING

SET  PATH=%PATH%;%CT_TOOL_DIR%;
SET  CT_OUTPUT_FLAGS_BACKUP=%CT_OUTPUT_FLAGS%
SET  CT_OUTPUT_FLAGS=X


REM =========================================================================
REM === Set the prefix string 

SET CT_SETENVVER_PREFIX=CExtend


REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - MODIFY_VERSION_PREFIX
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - MODIFY_VERSION_PREFIX



REM =========================================================================
REM === Generate a temp setenv.bat file, call it then remove it 

CT_VersionTool   .    -GenSetEnvBat  __Version_TemplateFile.bat    -GenSetEnvPrefix %CT_SETENVVER_PREFIX%
CALL             __Version_TemplateFile.bat
CT_Delete        __Version_TemplateFile.bat


REM =========================================================================
REM === All Done

GOTO  THE_END


REM =========================================================================
REM === Handle Errors

:ERROR_CTOOLS_MISSING
ECHO ERROR: CTools is not installed
GOTO THE_END


REM =========================================================================
REM === The End

:THE_END
SET  CT_OUTPUT_FLAGS=%CT_OUTPUT_FLAGS_BACKUP%
popd


