@ECHO OFF
SETLOCAL
REM =========================================================================
REM ===    Batch Filename: ZipUp.bat 
REM ===           Project: CT_ProjectConfig.ini 
REM ===  Project Filename: .\CT_ProjectConfig.ini 
REM =========================================================================
REM ===    Generated By: CT_BuildConfigTool (CToolsDev-v4.1.1.74) 
REM ===       Copyright: Copyright (c) 1995-2010, Colin Goodall, All Rights Reserved. 
REM ===         Version: CToolsDev-v4.1.1.74 
REM ===       Timestamp: 2025\09\26-23:54:13 utc 
REM =========================================================================


REM =========================================================================
REM === Initialize the environment

pushd  .

IF NOT EXIST "%CT_TOOL_DIR%" GOTO ERROR_CTOOLS_MISSING

SET  PATH=%PATH%;%CT_TOOL_DIR%;
SET  CT_OUTPUT_FLAGS=X


REM =========================================================================
REM === Clean The Project

@ECHO OFF
pushd . 
call Clean.bat 0
popd

CT_Printf " "  


REM =========================================================================
REM === Do the Zip 

set CT_OUTPUT_FLAGS=Z
CT_ZipDir .   -za  -d %1+5


REM =========================================================================
REM === All Done

GOTO  THE_END


REM =========================================================================
REM === Handle Errors

:ERROR_CTOOLS_MISSING
ECHO ERROR: CTools is not installed
GOTO THE_END


REM =========================================================================
REM === The End

:THE_END
ENDLOCAL
popd


