@ECHO OFF
SETLOCAL
REM =========================================================================
REM ===    Batch Filename: Rebuild.bat 
REM ===           Project: CT_ProjectConfig.ini 
REM ===  Project Filename: Applications\CT_ProjectConfig.ini 
REM =========================================================================
REM ===    Generated By: CT_BuildConfigTool (CToolsDev-v4.1.1.74) 
REM ===       Copyright: Copyright (c) 1995-2010, Colin Goodall, All Rights Reserved. 
REM ===         Version: CToolsDev-v4.1.1.74 
REM ===       Timestamp: 2025\09\26-17:03:09 utc 
REM =========================================================================


REM =========================================================================
REM === Initialize the environment

pushd  .

IF NOT EXIST "%CT_TOOL_DIR%" GOTO ERROR_CTOOLS_MISSING

SET  PATH=%PATH%;%CT_TOOL_DIR%;
SET  CT_OUTPUT_FLAGS=X


REM =========================================================================



REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - BEFORE_CLEAN_SUB_PROJECTS
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - BEFORE_CLEAN_SUB_PROJECTS



CALL  "Clean.bat" 



REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - BEFORE_BUILD_SUB_PROJECTS
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - BEFORE_BUILD_SUB_PROJECTS



CALL  "Build.bat" 



REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - AFTER_SUB_PROJECTS
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - AFTER_SUB_PROJECTS



REM =========================================================================
REM === All Done

GOTO  THE_END


REM =========================================================================
REM === Handle Errors

:ERROR_CTOOLS_MISSING
ECHO ERROR: CTools is not installed
GOTO THE_END


REM =========================================================================
REM === The End

:THE_END
ENDLOCAL
popd


