@ECHO OFF
SETLOCAL
REM =========================================================================
REM ===    Batch Filename: Clean.bat 
REM ===           Project: CT_ProjectConfig.ini 
REM ===  Project Filename: Libraries\CT_ProjectConfig.ini 
REM =========================================================================
REM ===    Generated By: CT_BuildConfigTool (CToolsDev-v4.1.1.74) 
REM ===       Copyright: Copyright (c) 1995-2010, Colin Goodall, All Rights Reserved. 
REM ===         Version: CToolsDev-v4.1.1.74 
REM ===       Timestamp: 2025\09\26-17:03:09 utc 
REM =========================================================================


REM =========================================================================
REM === Initialize the environment

pushd  .

IF NOT EXIST "%CT_TOOL_DIR%" GOTO ERROR_CTOOLS_MISSING

SET  PATH=%PATH%;%CT_TOOL_DIR%;
SET  CT_OUTPUT_FLAGS=X


REM =========================================================================

CT_Printf  -stdout "Cleaning == CExtend - Libraries " 



REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - BEFORE_SUB_PROJECTS
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - BEFORE_SUB_PROJECTS



REM -------------------------------------------------------------------------
REM --- CExBase
IF NOT EXIST "CExBase"             GOTO SKIP_01_CEXBASE 
IF NOT EXIST "CExBase\Clean.bat"   GOTO SKIP_01_CEXBASE 
PUSHD "CExBase" 
CALL  "Clean.bat" 
POPD 
GOTO  FINISH_01_CEXBASE
:SKIP_01_CEXBASE
CT_Printf  -stdout "ERROR:  Missing SubProject -- CExBase 
:FINISH_01_CEXBASE


REM -------------------------------------------------------------------------



REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - AFTER_SUB_PROJECTS
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - AFTER_SUB_PROJECTS



REM =========================================================================
REM === All Done

GOTO  THE_END


REM =========================================================================
REM === Handle Errors

:ERROR_CTOOLS_MISSING
ECHO ERROR: CTools is not installed
GOTO THE_END


REM =========================================================================
REM === The End

:THE_END
ENDLOCAL
popd


