@ECHO OFF
SETLOCAL
REM =========================================================================
REM ===    Batch Filename: Build_Win64_Debug.bat 
REM ===           Project: CExBase.vcproj 
REM ===  Project Filename: Libraries\CExBase\CExBase.vcproj 
REM ===          Platform: Win64 
REM ===            Target: Debug 
REM =========================================================================
REM ===    Generated By: CT_BuildConfigTool (CToolsDev-v4.1.1.74) 
REM ===       Copyright: Copyright (c) 1995-2010, Colin Goodall, All Rights Reserved. 
REM ===         Version: CToolsDev-v4.1.1.74 
REM ===       Timestamp: 2025\09\26-23:54:13 utc 
REM =========================================================================


REM =========================================================================
REM === Initialize the environment

pushd  .

IF NOT EXIST "%CT_TOOL_DIR%" GOTO ERROR_CTOOLS_MISSING

SET  PATH=%PATH%;%CT_TOOL_DIR%;
SET  CT_OUTPUT_FLAGS=X

CT_Delete   CT_SetupVSVars_TempOut.txt
CALL        CT_SetupVSVars.bat > CT_SetupVSVars_TempOut.txt
CT_Delete   CT_SetupVSVars_TempOut.txt


REM =========================================================================
REM === Do the Build

CT_Printf       -stdout "Building == CExtend - Libraries - CExBase - [Win64-Debug]" 



REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - PRE_BUILD_TARGET
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - PRE_BUILD_TARGET



CT_CreateDir   "..\..\Output\BuildLogs" 
CT_Delete      "..\..\Output\BuildLogs\CExtend_Libraries_CExBase.Win64.Debug.log" 

CT_Printf -stdout "============================================================================="  1>>    "..\..\Output\BuildLogs\CExtend_Libraries_CExBase.Win64.Debug.log"    2>&1 
CT_Printf -stdout "=== BUILD_TIMESTAMP_START=#@+c; "                                               1>>    "..\..\Output\BuildLogs\CExtend_Libraries_CExBase.Win64.Debug.log"    2>&1 
CT_Printf -stdout "=== BUILD_TITLE=CExBase "                                                       1>>    "..\..\Output\BuildLogs\CExtend_Libraries_CExBase.Win64.Debug.log"    2>&1 
CT_Printf -stdout "=== BUILD_TITLE_FULL=CExtend - Libraries - CExBase "                            1>>    "..\..\Output\BuildLogs\CExtend_Libraries_CExBase.Win64.Debug.log"    2>&1 
CT_Printf -stdout "=== BUILD_PLATFORM_TYPE=Win64 "                                                 1>>    "..\..\Output\BuildLogs\CExtend_Libraries_CExBase.Win64.Debug.log"    2>&1 
CT_Printf -stdout "=== BUILD_TARGET_TYPE=Debug "                                                   1>>    "..\..\Output\BuildLogs\CExtend_Libraries_CExBase.Win64.Debug.log"    2>&1 
CT_Printf -stdout "=== BUILD_PROJECT_FILE_TYPE=VCPROJ "                                            1>>    "..\..\Output\BuildLogs\CExtend_Libraries_CExBase.Win64.Debug.log"    2>&1 
CT_Printf -stdout "=== BUILD_PROJECT_FILE_NAME=Libraries\CExBase\CExBase.vcproj "                  1>>    "..\..\Output\BuildLogs\CExtend_Libraries_CExBase.Win64.Debug.log"    2>&1 
CT_Printf -stdout "=== BUILD_CONFIG_TOOL=CT_BuildConfigTool, CToolsDev-v4.1.1.74 "                 1>>    "..\..\Output\BuildLogs\CExtend_Libraries_CExBase.Win64.Debug.log"    2>&1 
CT_Printf -stdout "============================================================================="  1>>    "..\..\Output\BuildLogs\CExtend_Libraries_CExBase.Win64.Debug.log"    2>&1 
DevEnv  "CExBase.vcproj"  /BUILD  "Debug|x64"  /PROJECT  "CExBase"                                 1>>    "..\..\Output\BuildLogs\CExtend_Libraries_CExBase.Win64.Debug.log"    2>&1 
CT_Printf -stdout "============================================================================="  1>>    "..\..\Output\BuildLogs\CExtend_Libraries_CExBase.Win64.Debug.log"    2>&1 
CT_Printf -stdout "=== BUILD_TIMESTAMP_FINISH=#@+c; "                                              1>>    "..\..\Output\BuildLogs\CExtend_Libraries_CExBase.Win64.Debug.log"    2>&1 
CT_Printf -stdout "============================================================================="  1>>    "..\..\Output\BuildLogs\CExtend_Libraries_CExBase.Win64.Debug.log"    2>&1 

SET  CT_OUTPUT_FLAGS=
CT_BuildLog  "..\..\Output\BuildLogs\CExtend_Libraries_CExBase.Win64.Debug.log" 
SET  CT_OUTPUT_FLAGS=X



REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - POST_BUILD_TARGET
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - POST_BUILD_TARGET



REM =========================================================================
REM === All Done

GOTO  THE_END


REM =========================================================================
REM === Handle Errors

:ERROR_CTOOLS_MISSING
ECHO ERROR: CTools is not installed
GOTO THE_END


REM =========================================================================
REM === The End

:THE_END
ENDLOCAL
popd


