@ECHO OFF
SETLOCAL
REM =========================================================================
REM ===    Batch Filename: Rebuild.bat 
REM ===           Project: CExBase.vcproj 
REM ===  Project Filename: Libraries\CExBase\CExBase.vcproj 
REM =========================================================================
REM ===    Generated By: CT_BuildConfigTool (CToolsDev-v4.1.1.74) 
REM ===       Copyright: Copyright (c) 1995-2010, Colin Goodall, All Rights Reserved. 
REM ===         Version: CToolsDev-v4.1.1.74 
REM ===       Timestamp: 2025\09\26-22:22:41 utc 
REM =========================================================================


REM =========================================================================
REM === Initialize the environment

pushd  .


REM =========================================================================
REM === Do the Rebuild




REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - BEFORE_CLEAN_PROJECTS
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - BEFORE_CLEAN_PROJECTS



pushd   .
CALL Clean.bat
popd



REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - BEFORE_BUILD_PROJECTS
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - BEFORE_BUILD_PROJECTS



pushd   .
CALL Build.bat
popd



REM -----  CT_PROJECTTOOL_CUSTOM_LINES_START - POST_BUILD_PROJECTS
REM -----  CT_PROJECTTOOL_CUSTOM_LINES_END - POST_BUILD_PROJECTS




REM =========================================================================
REM === All Done

GOTO  THE_END


REM =========================================================================
REM === The End

:THE_END
ENDLOCAL
popd


